#!/bin/bash

# export NODE_VERSION="20.5.0"
export NODE_VERSION="22.16.0"

export DEV_TASKS="edit | test-watch"

export COV_BRANCHES=60
export COV_LINES=80
export COV_FUNCTIONS=80
export COV_STATEMENTS=80
